spring.application.name=FoodlyBusinessService

# Servidor
server.port=8082

# Base de Datos (MongoDB)
spring.data.mongodb.uri=mongodb://localhost:27017/foodly_business_db

# JWT
jwt.secret.key=f00dlyS3cr3tK3yF0rFoodN0d3Pl4tf0rm2025Lima
jwt.issuer=foodly-identity-service
jwt.expiration.minutes=60

# Springdoc OpenAPI (Swagger UI)
springdoc.api-docs.path=/openapi
springdoc.swagger-ui.path=/openapi-ui

# ActiveMQ
spring.activemq.broker-url=vm://localhost?broker.persistent=false
spring.jms.pub-sub-domain=false
